package com.finset.key_fin.coaching;

import com.finset.key_fin.global.exception.BusinessException;
import org.springframework.stereotype.Component;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.json.JsonMapper;
import tools.jackson.core.JacksonException;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpTimeoutException;
import java.time.Duration;
import java.util.HashSet;
import java.util.Map;
import java.util.stream.Stream;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;

/**
 * The app's JWT never reaches the inference service. The authenticated principal selects a
 * separately provisioned owner token; all paths below are generated by this module, not callers.
 */
@Component
public class CoachingClient {
    private static final int MAX_RESPONSE_BYTES = 8 * 1024 * 1024;
    private final CoachingProperties properties;
    private final Map<Long, String> userTokens;
    private final Map<Long, String> backendTokens;
    private final Map<Long, String> notificationTokens;
    private final JsonMapper mapper;
    private final HttpClient http;

    public CoachingClient(CoachingProperties properties, JsonMapper mapper) {
        this.properties = properties;
        this.mapper = mapper;
        this.userTokens = Map.copyOf(properties.getUserTokens());
        this.backendTokens = Map.copyOf(properties.getBackendTokens());
        this.notificationTokens = Map.copyOf(properties.getNotificationTokens());
        this.http = HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(5))
                .followRedirects(HttpClient.Redirect.NEVER).build();
        if (properties.isEnabled()) validateConfiguration();
    }

    private void validateConfiguration() {
        URI origin = properties.getBaseUrl();
        if (origin == null || origin.getHost() == null || origin.getRawUserInfo() != null
                || origin.getRawQuery() != null || origin.getRawFragment() != null
                || !("https".equals(origin.getScheme()) || "http".equals(origin.getScheme()))
                || !(origin.getPath().isEmpty() || "/".equals(origin.getPath()))) {
            throw new IllegalArgumentException("coaching.base-url must be a configured HTTP(S) origin");
        }
        if (properties.getTimeout().isNegative() || properties.getTimeout().isZero()
                || properties.getTimeout().compareTo(Duration.ofMinutes(2)) > 0) {
            throw new IllegalArgumentException("coaching.timeout must be greater than zero and at most two minutes");
        }
        var credentials = Stream.of(userTokens, backendTokens, notificationTokens).flatMap(tokens -> tokens.entrySet().stream()).toList();
        var tokens = credentials.stream().map(Map.Entry::getValue).toList();
        if (new HashSet<>(tokens).size() != tokens.size()
                || credentials.stream().anyMatch(entry -> entry.getKey() <= 0
                || entry.getValue().isBlank() || entry.getValue().contains("\n") || entry.getValue().contains("\r"))) {
            throw new IllegalArgumentException("AI tokens must be distinct, nonempty credentials per authenticated owner");
        }
    }

    public JsonNode get(Long userId, String path) {
        return send(userId, path, null, null, userTokens);
    }

    public JsonNode post(Long userId, String path, String requestKey, Object body) {
        return send(userId, path, requestKey, body, userTokens);
    }

    JsonNode postBackend(Long userId, String path, String requestKey, Object body) {
        return send(userId, path, requestKey, body, backendTokens);
    }

    JsonNode currentTwin(Long userId) { return send(userId, "/v1/twin", null, null, backendTokens); }

    public JsonNode notifications(Long userId) {
        return send(userId, "/v1/notifications", null, null, notificationTokens);
    }

    public JsonNode acknowledgeNotification(Long userId, String id, String requestKey) {
        if (id == null || !id.matches("[A-Za-z0-9_.-]{1,120}")) throw new BusinessException(CoachingErrorCode.INVALID_REQUEST);
        return send(userId, "/v1/notifications/" + id + "/ack", requestKey, Map.of(), notificationTokens);
    }

    private JsonNode send(Long userId, String path, String requestKey, Object body, Map<Long, String> tokens) {
        if (userId == null) throw new BusinessException(CoachingErrorCode.UNAUTHENTICATED);
        String token = tokens.get(userId);
        if (!properties.isEnabled() || token == null) throw new BusinessException(CoachingErrorCode.UNAVAILABLE);
        if (!path.startsWith("/v1/") || path.contains("..") || path.contains("?") || path.contains("#")) {
            throw new IllegalArgumentException("Only fixed coaching resource paths are allowed");
        }
        HttpRequest.Builder request = HttpRequest.newBuilder(properties.getBaseUrl().resolve(path))
                .timeout(properties.getTimeout()).header("Authorization", "Bearer " + token)
                .header("Accept", "application/json");
        if (body == null) request.GET();
        else {
            if (requestKey == null || !requestKey.matches("[A-Za-z0-9_.:-]{1,120}")) {
                throw new BusinessException(CoachingErrorCode.INVALID_REQUEST);
            }
            request.header("Idempotency-Key", requestKey).header("Content-Type", "application/json")
                    .POST(HttpRequest.BodyPublishers.ofString(mapper.writeValueAsString(body)));
        }
        var responseFuture = http.sendAsync(request.build(), ignored -> new LimitedResponseBody(MAX_RESPONSE_BYTES));
        try {
            // HttpRequest.timeout alone can finish at headers. This deadline includes the entire body.
            var response = responseFuture.get(Math.max(1, properties.getTimeout().toMillis()), TimeUnit.MILLISECONDS);
            if (response.statusCode() != 200) throw new BusinessException(upstreamError(response.statusCode()));
            JsonNode document = mapper.readTree(response.body());
            if (document == null || !document.isObject()) throw new BusinessException(CoachingErrorCode.UPSTREAM);
            return document;
        } catch (TimeoutException exception) {
            responseFuture.cancel(true);
            throw new BusinessException(CoachingErrorCode.TIMEOUT);
        } catch (ExecutionException exception) {
            throw new BusinessException(exception.getCause() instanceof HttpTimeoutException
                    ? CoachingErrorCode.TIMEOUT : CoachingErrorCode.UPSTREAM);
        } catch (JacksonException exception) {
            throw new BusinessException(CoachingErrorCode.UPSTREAM);
        } catch (InterruptedException exception) {
            responseFuture.cancel(true);
            Thread.currentThread().interrupt();
            throw new BusinessException(CoachingErrorCode.UPSTREAM);
        }
    }

    private CoachingErrorCode upstreamError(int status) {
        return switch (status) {
            case 400, 413, 422 -> CoachingErrorCode.INVALID_REQUEST;
            case 404, 410 -> CoachingErrorCode.NOT_FOUND;
            case 409 -> CoachingErrorCode.CONFLICT;
            case 429 -> CoachingErrorCode.TOO_MANY_REQUESTS;
            default -> CoachingErrorCode.UPSTREAM;
        };
    }
}
